FROM n8nio/n8n:latest

ARG PGPASSWORD
ARG PGHOST
ARG PGPORT
ARG PGDATABASE
ARG PGUSER

ENV DB_TYPE=postgresdb
ENV DB_POSTGRESDB_DATABASE=$PGDATABASE
ENV DB_POSTGRESDB_HOST=$PGHOST
ENV DB_POSTGRESDB_PORT=$PGPORT
ENV DB_POSTGRESDB_USER=$PGUSER
ENV DB_POSTGRESDB_PASSWORD=$PGPASSWORD


ARG ENCRYPTION_KEY

ENV N8N_ENCRYPTION_KEY=$ENCRYPTION_KEY

WORKDIR /home/nodes/
RUN npm install n8n-nodes-browserless
RUN npm install n8n-nodes-yaml
RUN npm install n8n-nodes-youtube-transcript
USER root
RUN npm install -g youtube-captions-scraper --unsafe-perm=true

CMD ["n8n start"]
